# Generated by Django 4.0 on 2022-04-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(default=None, max_length=5000),
        ),
    ]
