# Generated by Django 4.0 on 2022-05-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='items',
            field=models.CharField(default='{}', max_length=150),
        ),
    ]
