# Generated by Django 4.0 on 2022-05-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_commande_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='pricetotal',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
